stages:
  - build
  - deploy

build:
  stage: build
  tags:
    - se3
  script:
    - mvn clean package -D maven.test.skip=true
  artifacts:
    paths:
      - target/SentiStrength-backend-0.0.1-SNAPSHOT.jar

deploy-master:
  stage: deploy
  tags:
    - se3
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  when: manual
  script:
    - cd target
    - cp SentiStrength-backend-0.0.1-SNAPSHOT.jar /home/lighthouse/backend/Senti-backend-master.jar
    - cd /home/lighthouse/backend
    - sh init-dev.sh restart

deploy-dev:
  stage: deploy
  tags:
    - se3
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
  script:
    - cd target
    - cp SentiStrength-backend-0.0.1-SNAPSHOT.jar /home/lighthouse/backend/Senti-backend-dev.jar
    - cd /home/lighthouse/backend
    - sh init-master.sh restart
